import profile from '../assets/images/profile.png'
import bgAbout from '../assets/images/bgAbout.jpg'
import bgAbout2 from '../assets/images/bgAbout2.jpg'
import aboutImg from '../assets/images/aboutImg.png'
import delicieus from '../assets/images/projects/delicieus.png'
import design from '../assets/images/projects/design.png'
import loopstudios from '../assets/images/projects/loopstudios.png'
import moderna from '../assets/images/projects/moderna.png'
import siimple from '../assets/images/projects/siimple.png'
import Yummy from '../assets/images/projects/Yummy.png'
import array from '../assets/images/projects/array.png'
import doob from '../assets/images/projects/doob.png'
import sneakers from '../assets/images/projects/sneakers.png'
import tastbite from '../assets/images/projects/tastbite.png'
export default {profile, bgAbout, bgAbout2, aboutImg, delicieus, doob, Yummy, array, design, loopstudios, moderna, siimple, sneakers, tastbite}